### ISSUE TITLE
Dateien fehlen / sind falsch benannt.

### ISSUE THREAD

**Issue by urylux** [FrankSchoeneck/active_RT5#1]
Hallo Frank, vielen Dank für dein Theme, das ich schon seit einigen Jahren sehr gerne verwende. 
Ein kleiner Hinweis: Wenn ich in Locus beim Thema auf "Prüfen" gehe, bekomme ich folgende Fehlermeldung:

![image](https://github.com/FrankSchoeneck/active_RT5/assets/15878205/87846e5d-ff5b-46e8-8d89-43d83cd8d2c6)

Die Dateien sind alle vorhanden, aber etwas anders benannt (gray statt grey z.B.). Wenn ich sie entsprechend umbenenne läuft die Prüfung ohne Fehler durch.

**Comment by FrankSchoeneck** [comment]
Danke für den Hinweis, da hätte ich auch mal drauf kommen können, einfach mal in Locus auf prüfen drücken :-)
Habe gerade hier ein entsprechendes Update hochgeladen.
